### ISSUE TITLE
note operations not replicating on the frontend.

### ISSUE THREAD

**Issue by kgjika** [ComfortablyCoding/strapi-plugin-notes#3] opened 2022-05-23 14:28 UTC
https://user-images.githubusercontent.com/96471728/169840118-0f9acacf-4a44-47bd-a16c-9b4a65b5e783.mp4

> **Background:**

- I was trying to save some new Notes for my content and the note did not appear on screen after clicking Save.

> **Steps to reproduce:** 

After the plugin is installed:

- Click on Add a note.
- Write a Title for your note.
- Click on Save.

> **Actual result:**

- The note does not appear under the Notes section.

> **Expected result:**

- The note should be visible under the Notes section.

**Comment by ComfortablyCoding** [comment] 2022-05-23 17:50
Can you show the responses in the browser network tab for those API calls? Looks like something is failing.

**Comment by kgjika** [comment] 2022-05-24 09:45
Yes, if I refresh the page the change happens, the note gets deleted, but it is not the same case as the Save, Save behaves differently in a very weird way, sometimes it Saves and sometimes not... 

For example: I try to save a note and it does not appear on screen, then I try to save another note and they both appear at once.

Also the Network tab when I try to delete a note and then delete another one again: 
![1](https://user-images.githubusercontent.com/96471728/170002266-11cf5035-18c0-4a67-83ae-469283bb90be.png)


The Network tab when I try to edit a note and save it... after I pressed the delete button on the same note before hand.
![2](https://user-images.githubusercontent.com/96471728/170002599-cde31846-9f2b-4fcb-8875-dc73fa4edd2b.png)

**Comment by ComfortablyCoding** [comment] 2022-05-24 12:05
What version of the plugin are you on? And if possible can you provide the network requests tab for the failing save case as well?

**Comment by kgjika** [comment] 2022-05-24 12:19
I am on 
"@strapi/plugin-i18n": "4.0.3",    and 
"strapi-plugin-notes": "^1.0.1"

**Comment by ComfortablyCoding** [comment] 2022-05-25 12:04
Ok, will see if I can reproduce the issue.

**Comment by kgjika** [comment] 2022-05-30 14:20
Hello, I updated to the latest version of Strapi 4.1.12 and the issue with the deletions is still happening. Please fix it shortly.

**Comment by ComfortablyCoding** [comment] 2022-06-13 01:28
I am unable to reproduce this issue on my side, can you provide a repo with a reproducable example of this issue?

**Comment by ComfortablyCoding** [comment] 2022-07-27 01:58
Closing until reproducible example can be provided.

**Closed** 2022-07-27 01:58 UTC
